alias ls='ls -h --color=auto --group-directories-first'
alias l='ls -l'
alias la='ls -la'
alias c='clear'
alias cd..='cd ..'
alias aur='auracle -C /home/user/aur'
alias makepkg='makepkg -cris'
alias desktop_wake='wol MAC:ADDR:HERE'
alias ssh='TERM=xterm-256color ssh'
alias ip='ip -c'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
